### ISSUE TITLE
Buttons aren't showing for the SCD editor

### ISSUE THREAD

**Issue by fetchgames** [0ceal0t/Dalamud-VFXEditor#153]
![image](https://github.com/0ceal0t/Dalamud-VFXEditor/assets/106719731/aa25916c-265b-442c-8f28-3fb784bd75f8)

I'm trying to replace the mount music and nothing is showing up when i do it please help!

**Comment by StoiaCode** [comment]
Yeah having the same issue for all Local/ Penumbra .scd files. Additonally it says error reading file 
![grafik](https://github.com/0ceal0t/Dalamud-VFXEditor/assets/23234609/ee7bb1dc-906b-4450-875e-cda6a3cfa183)

**Comment by StoiaCode** [comment]
same issue as #120

**Comment by 0ceal0t** [comment]
yeah this is a common issue with modded scd files generated by other tools since they generally don't adhere to the same formatting as SE does. Could you send me some examples so I can take a look?

Feel free to drop them directly in the `VFXEditor` channel in the Quicklauncher discord, or message me directly

**Comment by fetchgames** [comment]
sure thing! Mind if I message you on discord?

**Comment by StoiaCode** [comment]
Works for me now! Now just to figure out if I can change what channel a song plays on...
