### ISSUE TITLE
Question - Ending a seemingly infinite VFX

### ISSUE THREAD

**Issue by Izedra** [0ceal0t/Dalamud-VFXEditor#38]
I am trying to use the vfx `vfx/common/eff/ystr_castx0h.avfx` instead of `Pulse of Life #2`, but it has the problem that this vfx seems infinite, like is on an eternal loop, I mean, it never ends, just stays there... Menacingly...

Is there any way to end it whenever you want? I swear I tryed everything I thought about but did not obtain any result.

**Comment by 0ceal0t** [comment]
making a VFX with an unbounded time only last for a certain duration (in this case) or vice-versa is always kind of scuffed. The "easy" way in this case is to create a new item in the scheduler which triggers "timeline #2", and adjust the start time to whatever you want.

![unlock_loop_point_1](https://user-images.githubusercontent.com/18051158/161449305-9ea6b2ee-5435-470b-b898-39393fe6ba73.PNG)

This works because timeline 2 has clips of type "unlock loop point" and "kill"

![unlock_loop_point_2](https://user-images.githubusercontent.com/18051158/161449327-682c7503-c3f9-43ba-8ae6-a48de1f1a724.PNG)

you should probably also clear out the "triggers" of the scheduler and set all of the timelines to "[NONE]"

![unlock_loop_point_3](https://user-images.githubusercontent.com/18051158/161449373-17f35297-fa26-4dde-908d-68d70e2e5897.PNG)

**Comment by 0ceal0t** [comment]
the "proper" way I guess is to adjust the "create interval", "create count", and "life" attributes of each of the particles, emitters, and timeline items

**Comment by Izedra** [comment]
Oh f*ck, it works... Not that I doubt about your response, but seeing it first hand after me failing so hard is... Amusing. Working with this plug-in, in general, is pretty entertaining.

About the "proper" way, the thing is that there is a lot sof the same just with different number at the end... I tried before posting the question, but I am sure that I missed some of the options.

BTW, is this solution aplicable to other VFXs? I understand that it works because the `timeline 2` of the effect have that "Ulock Loop Point" clip, right?

**Comment by 0ceal0t** [comment]
This should work for other "infinite" vfxs. If they don't have something like "timeline 2", you can just create a new timeline and add "unlock loop point" and "kill" clips to it with the same parameters.
