### ISSUE TITLE
[Question] Can it possible to stop vfx when I'm interrupted or casting? 

### ISSUE THREAD

**Issue by turturly** [0ceal0t/Dalamud-VFXEditor#67]
Similar to LB3 that when you walk while casting, the vfx of casting will disappear.
I want to know how to setting it. I put a boss charging skill vfx to my LB3 casting but when I move while casting, it still stay until the base time of boss skill end.

**Comment by XCZA** [comment]
So the way that is handled with the Limit breaks is there are multiple animations. a 'wind up' animation that starts the cast but also doesn't go so far into the VFX that if you cancel it, it just looks like it fizzes out. It's a bit tricky and annoying because the cast is the longest part of the animation so you gotta backload a lot of the vfx. LB3 has a much longer animation lock, so there is more time to do all your post-wind up vfx during the actual animation lock.

**Comment by turturly** [comment]
Sorry, I'm still a bit confused. That you gonna say is it can do but it's too complicated about changing another VFX to be LB3 casting animation(the one that when I move, VFX will fade out )?
I want to do like...For example, DRG LB3, the casting one which has dragon head come out while casting, but it'll fade out when I move my character.
Could you tell me which options in VFXEditor I can change it?

**Comment by XCZA** [comment]
what ability are you actually trying to change? unless its a limit break that will not work on most actions unless you modify the actual casting animation (which i dont recommend since you cannot change that pap without also changing hundreds of other animations). 

a non LB action is usually split between:
- start (the cast animation) - most jobs have a few different ones, happens during the cast bar.
- end (the actual unique vfx for that action)
- hit (impact on target) many actions do not actually have unique hit avfx, and use default ones
- loop (if an action has a looping animation) many actions do not have loops, but some do like meditate, improv, anatman 

LB's have unique start animations that are not used for any other actions, so you can saftely modify them. the Lb1 and Lb2 start animations are shared, but LB3 start is totally unique. So any animation you do for lb1 you prob should do for lb2.

**Comment by turturly** [comment]
I'm trying to use Nidstinien one which is the opening before phase 2 start in The Final Steps of Faith. 
Also, thank you so much. I think I'll use the current one or another classes LB casting, and change color instead.
